export { default as Dashboard } from "./dashboard/DashboardScreen";
export { default as Teachers } from "./teachers/TeachersScreen";
export { default as PageNotFound } from "./error/PageNotFound";
export { default as StudentsScreen } from "./students/StudentsScreen";
export { default as MessageScreen } from "./message/MessageScreen";
export { default as Payments} from "./payment/PaymentScreen";
export { default as GenerateQR} from "./qr/GenerateQR";
export { default as GetStudentsAttendance} from "./qrscanner/AttendanceScreen";
export { default as StudentEnroll} from "./enroll/StudentEnrollScreen";
export { default as ReportScreen} from "./report/ReportScreen";